service:
  name: 'planningUser'
  port: 7003
  env: 'DEV'

bbs:
  name: 'Ads Server'

default:
  bbs: 'wa'
  sub: 'fr'

i18n:
  default: 'fr'

jwt:
  secret: 'jlvghjkfvJKHFVJKYTFfdfgdfgdyertyery'
